name: 'Ajv validate JSON(s)'
description: 'Validate JSON(s) by given schema using Ajv schema validator'
author: 'vanekj'
inputs:
  pattern:
    description: 'Glob pattern to the JSON(s) to validate (eg. data/**/*.json)'
    required: true
outputs:
  result:
    description: 'Relative paths to the invalid JSON(s)'
runs:
  using: 'node16'
  main: '.dist/index.js'
branding:
  icon: 'search'
  color: 'green'
