name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '!.dist/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint
